# Generated by Django 5.2 on 2025-08-18 18:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0001_initial'),
        ('usuarios', '0003_estudiante_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='gac',
            options={'ordering': ['numero'], 'verbose_name': 'GAC', 'verbose_name_plural': 'GACs'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='rac',
            options={'ordering': ['numero'], 'verbose_name': 'RAC', 'verbose_name_plural': 'RACs'},
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='usuarios.estudiante', verbose_name='Estudiante evaluado'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL, verbose_name='Profesor evaluador'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='puntaje',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, message='El puntaje mínimo es 0.0'), django.core.validators.MaxValueValidator(5.0, message='El puntaje máximo es 5.0')], verbose_name='Puntaje de evaluación'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='rac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='competencias.rac', verbose_name='RAC evaluado'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacion',
            unique_together={('estudiante', 'rac', 'profesor')},
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['estudiante', 'rac'], name='competencia_estudia_3717c5_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['profesor', 'estudiante'], name='competencia_profeso_20d7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['fecha'], name='competencia_fecha_e3a08b_idx'),
        ),
    ]
