# Generated by Django 5.2 on 2025-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0002_alter_evaluacion_options_alter_gac_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='puntaje',
            field=models.IntegerField(choices=[(1, '1 - Insuficiente'), (2, '2 - Básico'), (3, '3 - Satisfactorio'), (4, '4 - Bueno'), (5, '5 - Excelente')], verbose_name='Puntaje de evaluación'),
        ),
    ]
