# Generated by Django 5.2 on 2025-06-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Documento de identidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('grupo', models.CharField(max_length=50, verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='profesor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
