# Generated by Django 5.2 on 2025-06-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estudiante_alter_profesor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(choices=[('prematricula', 'Prematriculado'), ('matriculado', 'Matriculado')], default='prematricula', max_length=15, verbose_name='Estado de matrícula'),
        ),
    ]
