# Generated by Django 5.2 on 2025-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_estudiante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profesores_fotos/', verbose_name='Foto del profesor'),
        ),
    ]
